[project]
name = "0918-class-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ch7272", email = "the.penguin7222@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
0918-class-practice = "0918_class_practice:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
